// <auto-generated />
using System;
using Banking_Payments.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banking_Payments.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251031065534_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Banking_Payments.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Code = "ADM001",
                            Email = "alice@banking.com",
                            Name = "Alice Johnson",
                            Password = "Pass@123"
                        },
                        new
                        {
                            AdminId = 2,
                            Code = "ADM002",
                            Email = "bob@banking.com",
                            Name = "Bob Smith",
                            Password = "Pass@123"
                        },
                        new
                        {
                            AdminId = 3,
                            Code = "ADM003",
                            Email = "charlie@banking.com",
                            Name = "Charlie Brown",
                            Password = "Pass@123"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BankId");

                    b.HasIndex("AdminId");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            BankId = 1,
                            Address = "123 Finance St",
                            AdminId = 1,
                            Code = "B001",
                            ContactEmail = "info@fnb.com",
                            ContactPhone = "1234567890",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "First National Bank",
                            PanNumber = "AAAPL1234C",
                            RegistrationNumber = "REG001"
                        },
                        new
                        {
                            BankId = 2,
                            Address = "456 Trust Ave",
                            AdminId = 2,
                            Code = "B002",
                            ContactEmail = "contact@gtb.com",
                            ContactPhone = "9876543210",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Global Trust Bank",
                            PanNumber = "BBBTY4567P",
                            RegistrationNumber = "REG002"
                        },
                        new
                        {
                            BankId = 3,
                            Address = "789 Metro Rd",
                            AdminId = 3,
                            Code = "B003",
                            ContactEmail = "support@mfb.com",
                            ContactPhone = "5647382910",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Metro Finance Bank",
                            PanNumber = "CCCXY7890K",
                            RegistrationNumber = "REG003"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.BankUser", b =>
                {
                    b.Property<int>("BankUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankUserId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BankUserId");

                    b.HasIndex("BankId");

                    b.ToTable("BankUsers");

                    b.HasData(
                        new
                        {
                            BankUserId = 1,
                            BankId = 1,
                            Code = "BU001",
                            Email = "emma@fnb.com",
                            Name = "Emma Green",
                            Password = "123456",
                            PhoneNumber = "9876543210"
                        },
                        new
                        {
                            BankUserId = 2,
                            BankId = 2,
                            Code = "BU002",
                            Email = "liam@gtb.com",
                            Name = "Liam Gray",
                            Password = "123456",
                            PhoneNumber = "8765432109"
                        },
                        new
                        {
                            BankUserId = 3,
                            BankId = 3,
                            Code = "BU003",
                            Email = "olivia@mfb.com",
                            Name = "Olivia White",
                            Password = "123456",
                            PhoneNumber = "7654321098"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Beneficiary", b =>
                {
                    b.Property<int>("BeneficiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficiaryId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId1")
                        .HasColumnType("int");

                    b.Property<string>("IfscCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeneficiaryId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientId1");

                    b.ToTable("Beneficiaries");

                    b.HasData(
                        new
                        {
                            BeneficiaryId = 1,
                            AccountNumber = "1234567890",
                            ClientId = 1,
                            IfscCode = "FNB0001",
                            Name = "John Doe"
                        },
                        new
                        {
                            BeneficiaryId = 2,
                            AccountNumber = "2345678901",
                            ClientId = 2,
                            IfscCode = "GTB0002",
                            Name = "Mary Jane"
                        },
                        new
                        {
                            BeneficiaryId = 3,
                            AccountNumber = "3456789012",
                            ClientId = 3,
                            IfscCode = "MFB0003",
                            Name = "Peter Parker"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("BankUserId")
                        .HasColumnType("int");

                    b.Property<string>("ClientAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientBusinessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientVerificationStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.HasIndex("BankId");

                    b.HasIndex("BankUserId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            BankId = 1,
                            BankUserId = 1,
                            ClientAddress = "12 Silicon Ave",
                            ClientBusinessType = "IT Services",
                            ClientCode = "C001",
                            ClientEmail = "hr@techwave.com",
                            ClientName = "TechWave Ltd",
                            ClientVerificationStatus = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Password = "client123"
                        },
                        new
                        {
                            ClientId = 2,
                            BankId = 2,
                            BankUserId = 2,
                            ClientAddress = "45 Organic Rd",
                            ClientBusinessType = "Food Manufacturing",
                            ClientCode = "C002",
                            ClientEmail = "admin@greenfoods.com",
                            ClientName = "GreenFoods Inc",
                            ClientVerificationStatus = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Password = "client123"
                        },
                        new
                        {
                            ClientId = 3,
                            BankId = 3,
                            BankUserId = 3,
                            ClientAddress = "78 Brick Lane",
                            ClientBusinessType = "Construction",
                            ClientCode = "C003",
                            ClientEmail = "info@urbanbuilders.com",
                            ClientName = "Urban Builders",
                            ClientVerificationStatus = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Password = "client123"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.ContactDetails", b =>
                {
                    b.Property<int>("ContactDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactDetailsId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ContactDetailsId");

                    b.HasIndex("BankId");

                    b.ToTable("ContactDetails");

                    b.HasData(
                        new
                        {
                            ContactDetailsId = 1,
                            BankId = 1,
                            ContactEmail = "tom@fnb.com",
                            ContactName = "Tom Hardy",
                            ContactNumber = "9998887771",
                            IsActive = true
                        },
                        new
                        {
                            ContactDetailsId = 2,
                            BankId = 2,
                            ContactEmail = "anna@gtb.com",
                            ContactName = "Anna Scott",
                            ContactNumber = "9998887772",
                            IsActive = true
                        },
                        new
                        {
                            ContactDetailsId = 3,
                            BankId = 3,
                            ContactEmail = "chris@mfb.com",
                            ContactName = "Chris Evans",
                            ContactNumber = "9998887773",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("BankUserId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("DocType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.HasIndex("BankUserId");

                    b.HasIndex("ClientId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            DocumentId = 1,
                            BankUserId = 1,
                            ClientId = 1,
                            Name = "PAN Proof",
                            UploadedAt = new DateTime(2025, 10, 31, 6, 55, 34, 221, DateTimeKind.Utc).AddTicks(8622),
                            Url = "/docs/pan1.pdf"
                        },
                        new
                        {
                            DocumentId = 2,
                            BankUserId = 2,
                            ClientId = 2,
                            Name = "Registration Cert",
                            UploadedAt = new DateTime(2025, 10, 31, 6, 55, 34, 221, DateTimeKind.Utc).AddTicks(9913),
                            Url = "/docs/reg2.pdf"
                        },
                        new
                        {
                            DocumentId = 3,
                            BankUserId = 3,
                            ClientId = 3,
                            Name = "Address Proof",
                            UploadedAt = new DateTime(2025, 10, 31, 6, 55, 34, 221, DateTimeKind.Utc).AddTicks(9915),
                            Url = "/docs/address3.pdf"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("IfscCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ClientId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            AccountNumber = "9876543210",
                            Address = "101 Lakeview",
                            ClientId = 1,
                            IfscCode = "FNB0001",
                            Name = "Sarah Wilson",
                            Salary = 50000m
                        },
                        new
                        {
                            EmployeeId = 2,
                            AccountNumber = "8765432109",
                            Address = "202 Hilltop",
                            ClientId = 2,
                            IfscCode = "GTB0002",
                            Name = "David Lee",
                            Salary = 45000m
                        },
                        new
                        {
                            EmployeeId = 3,
                            AccountNumber = "7654321098",
                            Address = "303 Park St",
                            ClientId = 3,
                            IfscCode = "MFB0003",
                            Name = "Sophia Brown",
                            Salary = 55000m
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BankUserId")
                        .HasColumnType("int");

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("BankUserId");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("ClientId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 10000m,
                            BankUserId = 1,
                            BeneficiaryId = 1,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 25000m,
                            BankUserId = 2,
                            BeneficiaryId = 2,
                            ClientId = 2,
                            PaymentDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 5000m,
                            BankUserId = 3,
                            BeneficiaryId = 3,
                            ClientId = 3,
                            PaymentDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            status = 0
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.SalaryDisbursement", b =>
                {
                    b.Property<int>("SalaryDisbursementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryDisbursementId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("SalaryDisbursementId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryDisbursements");

                    b.HasData(
                        new
                        {
                            SalaryDisbursementId = 1,
                            Amount = 50000m,
                            ClientId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1
                        },
                        new
                        {
                            SalaryDisbursementId = 2,
                            Amount = 45000m,
                            ClientId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2
                        },
                        new
                        {
                            SalaryDisbursementId = 3,
                            Amount = 55000m,
                            ClientId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Bank", b =>
                {
                    b.HasOne("Banking_Payments.Models.Admin", "Admin")
                        .WithMany("Banks")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Banking_Payments.Models.BankUser", b =>
                {
                    b.HasOne("Banking_Payments.Models.Bank", "Bank")
                        .WithMany("BankUsers")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Banking_Payments.Models.Beneficiary", b =>
                {
                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.Client", null)
                        .WithMany("Beneficiaries")
                        .HasForeignKey("ClientId1");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Banking_Payments.Models.Client", b =>
                {
                    b.HasOne("Banking_Payments.Models.Bank", "Bank")
                        .WithMany("Clients")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.BankUser", "BankUser")
                        .WithMany("Clients")
                        .HasForeignKey("BankUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("BankUser");
                });

            modelBuilder.Entity("Banking_Payments.Models.ContactDetails", b =>
                {
                    b.HasOne("Banking_Payments.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Banking_Payments.Models.Document", b =>
                {
                    b.HasOne("Banking_Payments.Models.BankUser", "UploadedBy")
                        .WithMany("Documents")
                        .HasForeignKey("BankUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany("Documents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Banking_Payments.Models.Employee", b =>
                {
                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany("Employees")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Banking_Payments.Models.Payment", b =>
                {
                    b.HasOne("Banking_Payments.Models.BankUser", "ApprovedBy")
                        .WithMany("Payments")
                        .HasForeignKey("BankUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.Beneficiary", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Beneficiary");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Banking_Payments.Models.SalaryDisbursement", b =>
                {
                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany("SalaryDisbursement")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.Employee", "Employee")
                        .WithMany("SalaryDisbursements")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Banking_Payments.Models.Admin", b =>
                {
                    b.Navigation("Banks");
                });

            modelBuilder.Entity("Banking_Payments.Models.Bank", b =>
                {
                    b.Navigation("BankUsers");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Banking_Payments.Models.BankUser", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Documents");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Banking_Payments.Models.Client", b =>
                {
                    b.Navigation("Beneficiaries");

                    b.Navigation("Documents");

                    b.Navigation("Employees");

                    b.Navigation("Payments");

                    b.Navigation("SalaryDisbursement");
                });

            modelBuilder.Entity("Banking_Payments.Models.Employee", b =>
                {
                    b.Navigation("SalaryDisbursements");
                });
#pragma warning restore 612, 618
        }
    }
}
