// <auto-generated />
using System;
using Banking_Payments.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banking_Payments.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104134928_updated-client")]
    partial class updatedclient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Banking_Payments.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Code = "ADM001",
                            Email = "alice@banking.com",
                            Name = "Alice Johnson",
                            Password = "Pass@123"
                        },
                        new
                        {
                            AdminId = 2,
                            Code = "ADM002",
                            Email = "bob@banking.com",
                            Name = "Bob Smith",
                            Password = "Pass@123"
                        },
                        new
                        {
                            AdminId = 3,
                            Code = "ADM003",
                            Email = "charlie@banking.com",
                            Name = "Charlie Brown",
                            Password = "Pass@123"
                        },
                        new
                        {
                            AdminId = 4,
                            Code = "ADM004",
                            Email = "diana@banking.com",
                            Name = "Diana Prince",
                            Password = "Pass@123"
                        },
                        new
                        {
                            AdminId = 5,
                            Code = "ADM005",
                            Email = "ethan@banking.com",
                            Name = "Ethan Hunt",
                            Password = "Pass@123"
                        },
                        new
                        {
                            AdminId = 6,
                            Code = "ADM006",
                            Email = "fiona@banking.com",
                            Name = "Fiona Carter",
                            Password = "Pass@123"
                        },
                        new
                        {
                            AdminId = 7,
                            Code = "ADM007",
                            Email = "george@banking.com",
                            Name = "George Miller",
                            Password = "Pass@123"
                        },
                        new
                        {
                            AdminId = 8,
                            Code = "ADM008",
                            Email = "hannah@banking.com",
                            Name = "Hannah Wells",
                            Password = "Pass@123"
                        },
                        new
                        {
                            AdminId = 9,
                            Code = "ADM009",
                            Email = "ian@banking.com",
                            Name = "Ian Holmes",
                            Password = "Pass@123"
                        },
                        new
                        {
                            AdminId = 10,
                            Code = "ADM010",
                            Email = "julia@banking.com",
                            Name = "Julia Roberts",
                            Password = "Pass@123"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BankId");

                    b.HasIndex("AdminId");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            BankId = 1,
                            Address = "123 Finance St",
                            AdminId = 1,
                            Code = "B001",
                            ContactEmail = "info@fnb.com",
                            ContactPhone = "1234567890",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(825),
                            IsActive = true,
                            Name = "First National Bank",
                            PanNumber = "AAAPL1234C",
                            RegistrationNumber = "REG001"
                        },
                        new
                        {
                            BankId = 2,
                            Address = "456 Trust Ave",
                            AdminId = 2,
                            Code = "B002",
                            ContactEmail = "contact@gtb.com",
                            ContactPhone = "9876543210",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(1132),
                            IsActive = true,
                            Name = "Global Trust Bank",
                            PanNumber = "BBBTY4567P",
                            RegistrationNumber = "REG002"
                        },
                        new
                        {
                            BankId = 3,
                            Address = "789 Metro Rd",
                            AdminId = 3,
                            Code = "B003",
                            ContactEmail = "support@mfb.com",
                            ContactPhone = "5647382910",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(1135),
                            IsActive = true,
                            Name = "Metro Finance Bank",
                            PanNumber = "CCCXY7890K",
                            RegistrationNumber = "REG003"
                        },
                        new
                        {
                            BankId = 4,
                            Address = "88 Liberty Ln",
                            AdminId = 4,
                            Code = "B004",
                            ContactEmail = "help@unity.com",
                            ContactPhone = "9898989898",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(1137),
                            IsActive = true,
                            Name = "Unity Bank",
                            PanNumber = "DDDPL2234J",
                            RegistrationNumber = "REG004"
                        },
                        new
                        {
                            BankId = 5,
                            Address = "22 Market Rd",
                            AdminId = 5,
                            Code = "B005",
                            ContactEmail = "info@ccb.com",
                            ContactPhone = "9000090000",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(1139),
                            IsActive = true,
                            Name = "Central Credit Bank",
                            PanNumber = "EEERW5567L",
                            RegistrationNumber = "REG005"
                        },
                        new
                        {
                            BankId = 6,
                            Address = "47 Prime Blvd",
                            AdminId = 6,
                            Code = "B006",
                            ContactEmail = "contact@prime.com",
                            ContactPhone = "8765432190",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(1164),
                            IsActive = true,
                            Name = "Prime Finance Corp",
                            PanNumber = "FFFTR2233N",
                            RegistrationNumber = "REG006"
                        },
                        new
                        {
                            BankId = 7,
                            Address = "12 Green St",
                            AdminId = 7,
                            Code = "B007",
                            ContactEmail = "eco@esb.com",
                            ContactPhone = "9123456789",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(1166),
                            IsActive = true,
                            Name = "Eco Savings Bank",
                            PanNumber = "GGGTY8907M",
                            RegistrationNumber = "REG007"
                        },
                        new
                        {
                            BankId = 8,
                            Address = "7 Freedom Way",
                            AdminId = 8,
                            Code = "B008",
                            ContactEmail = "info@liberty.com",
                            ContactPhone = "9234567890",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(1168),
                            IsActive = true,
                            Name = "Liberty Bank",
                            PanNumber = "HHHPL5678V",
                            RegistrationNumber = "REG008"
                        },
                        new
                        {
                            BankId = 9,
                            Address = "4 Heritage Square",
                            AdminId = 9,
                            Code = "B009",
                            ContactEmail = "support@heritage.com",
                            ContactPhone = "9345678901",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(1170),
                            IsActive = true,
                            Name = "Heritage Finance",
                            PanNumber = "IIIWR3456C",
                            RegistrationNumber = "REG009"
                        },
                        new
                        {
                            BankId = 10,
                            Address = "55 Moonlight Rd",
                            AdminId = 10,
                            Code = "B010",
                            ContactEmail = "hello@crescent.com",
                            ContactPhone = "9456789012",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(1172),
                            IsActive = true,
                            Name = "Crescent Capital Bank",
                            PanNumber = "JJJER5647R",
                            RegistrationNumber = "REG010"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.BankUser", b =>
                {
                    b.Property<int>("BankUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankUserId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BankUserId");

                    b.HasIndex("BankId");

                    b.ToTable("BankUsers");

                    b.HasData(
                        new
                        {
                            BankUserId = 1,
                            BankId = 1,
                            Code = "BU001",
                            Email = "emma@fnb.com",
                            Name = "Emma Green",
                            Password = "123456",
                            PhoneNumber = "9876543210"
                        },
                        new
                        {
                            BankUserId = 2,
                            BankId = 2,
                            Code = "BU002",
                            Email = "liam@gtb.com",
                            Name = "Liam Gray",
                            Password = "123456",
                            PhoneNumber = "8765432109"
                        },
                        new
                        {
                            BankUserId = 3,
                            BankId = 3,
                            Code = "BU003",
                            Email = "olivia@mfb.com",
                            Name = "Olivia White",
                            Password = "123456",
                            PhoneNumber = "7654321098"
                        },
                        new
                        {
                            BankUserId = 4,
                            BankId = 4,
                            Code = "BU004",
                            Email = "noah@unity.com",
                            Name = "Noah Black",
                            Password = "123456",
                            PhoneNumber = "6543210987"
                        },
                        new
                        {
                            BankUserId = 5,
                            BankId = 5,
                            Code = "BU005",
                            Email = "ava@ccb.com",
                            Name = "Ava Brown",
                            Password = "123456",
                            PhoneNumber = "5432109876"
                        },
                        new
                        {
                            BankUserId = 6,
                            BankId = 6,
                            Code = "BU006",
                            Email = "will@prime.com",
                            Name = "William Scott",
                            Password = "123456",
                            PhoneNumber = "4321098765"
                        },
                        new
                        {
                            BankUserId = 7,
                            BankId = 7,
                            Code = "BU007",
                            Email = "sophia@eco.com",
                            Name = "Sophia Adams",
                            Password = "123456",
                            PhoneNumber = "3210987654"
                        },
                        new
                        {
                            BankUserId = 8,
                            BankId = 8,
                            Code = "BU008",
                            Email = "james@liberty.com",
                            Name = "James Walker",
                            Password = "123456",
                            PhoneNumber = "2109876543"
                        },
                        new
                        {
                            BankUserId = 9,
                            BankId = 9,
                            Code = "BU009",
                            Email = "mia@heritage.com",
                            Name = "Mia Turner",
                            Password = "123456",
                            PhoneNumber = "1098765432"
                        },
                        new
                        {
                            BankUserId = 10,
                            BankId = 10,
                            Code = "BU010",
                            Email = "lucas@crescent.com",
                            Name = "Lucas Reed",
                            Password = "123456",
                            PhoneNumber = "9988776655"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Beneficiary", b =>
                {
                    b.Property<int>("BeneficiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficiaryId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId1")
                        .HasColumnType("int");

                    b.Property<string>("IfscCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeneficiaryId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientId1");

                    b.ToTable("Beneficiaries");

                    b.HasData(
                        new
                        {
                            BeneficiaryId = 1,
                            AccountNumber = "1234567890",
                            ClientId = 1,
                            IfscCode = "FNB0001",
                            Name = "John Doe"
                        },
                        new
                        {
                            BeneficiaryId = 2,
                            AccountNumber = "2345678901",
                            ClientId = 2,
                            IfscCode = "GTB0002",
                            Name = "Mary Jane"
                        },
                        new
                        {
                            BeneficiaryId = 3,
                            AccountNumber = "3456789012",
                            ClientId = 3,
                            IfscCode = "MFB0003",
                            Name = "Peter Parker"
                        },
                        new
                        {
                            BeneficiaryId = 4,
                            AccountNumber = "4567890123",
                            ClientId = 4,
                            IfscCode = "UNITY0004",
                            Name = "Tony Stark"
                        },
                        new
                        {
                            BeneficiaryId = 5,
                            AccountNumber = "5678901234",
                            ClientId = 5,
                            IfscCode = "CCB0005",
                            Name = "Bruce Wayne"
                        },
                        new
                        {
                            BeneficiaryId = 6,
                            AccountNumber = "6789012345",
                            ClientId = 6,
                            IfscCode = "PRIME0006",
                            Name = "Clark Kent"
                        },
                        new
                        {
                            BeneficiaryId = 7,
                            AccountNumber = "7890123456",
                            ClientId = 7,
                            IfscCode = "ECO0007",
                            Name = "Diana Prince"
                        },
                        new
                        {
                            BeneficiaryId = 8,
                            AccountNumber = "8901234567",
                            ClientId = 8,
                            IfscCode = "LIB0008",
                            Name = "Barry Allen"
                        },
                        new
                        {
                            BeneficiaryId = 9,
                            AccountNumber = "9012345678",
                            ClientId = 9,
                            IfscCode = "HER0009",
                            Name = "Hal Jordan"
                        },
                        new
                        {
                            BeneficiaryId = 10,
                            AccountNumber = "0123456789",
                            ClientId = 10,
                            IfscCode = "CRES00010",
                            Name = "Arthur Curry"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("BankUserId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfscCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisterationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("BankId");

                    b.HasIndex("BankUserId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "12 Silicon Ave",
                            Balance = 0.0,
                            BankId = 1,
                            BankUserId = 1,
                            BusinessType = "IT Services",
                            Code = "C001",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(4456),
                            Email = "hr@techwave.com",
                            IsActive = true,
                            Name = "TechWave Ltd",
                            Password = "client123",
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            ClientId = 2,
                            Address = "45 Organic Rd",
                            Balance = 0.0,
                            BankId = 2,
                            BankUserId = 2,
                            BusinessType = "Food Manufacturing",
                            Code = "C002",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(4847),
                            Email = "admin@greenfoods.com",
                            IsActive = true,
                            Name = "GreenFoods Inc",
                            Password = "client123",
                            VerificationStatus = "Pending"
                        },
                        new
                        {
                            ClientId = 3,
                            Address = "78 Brick Lane",
                            Balance = 0.0,
                            BankId = 3,
                            BankUserId = 3,
                            BusinessType = "Construction",
                            Code = "C003",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(4849),
                            Email = "info@urbanbuilders.com",
                            IsActive = true,
                            Name = "Urban Builders",
                            Password = "client123",
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            ClientId = 4,
                            Address = "22 Sea View",
                            Balance = 0.0,
                            BankId = 4,
                            BankUserId = 4,
                            BusinessType = "Travel Agency",
                            Code = "C004",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(4852),
                            Email = "info@blueocean.com",
                            IsActive = true,
                            Name = "BlueOcean Travels",
                            Password = "client123",
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            ClientId = 5,
                            Address = "88 Medic Way",
                            Balance = 0.0,
                            BankId = 5,
                            BankUserId = 5,
                            BusinessType = "Pharmaceuticals",
                            Code = "C005",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(4854),
                            Email = "contact@healthplus.com",
                            IsActive = true,
                            Name = "HealthPlus Pharma",
                            Password = "client123",
                            VerificationStatus = "Pending"
                        },
                        new
                        {
                            ClientId = 6,
                            Address = "91 Knowledge Park",
                            Balance = 0.0,
                            BankId = 6,
                            BankUserId = 6,
                            BusinessType = "Education",
                            Code = "C006",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(4855),
                            Email = "hello@brightfuture.com",
                            IsActive = true,
                            Name = "BrightFuture EdTech",
                            Password = "client123",
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            ClientId = 7,
                            Address = "32 Green Fields",
                            Balance = 0.0,
                            BankId = 7,
                            BankUserId = 7,
                            BusinessType = "Agriculture",
                            Code = "C007",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(4857),
                            Email = "info@ecofarm.com",
                            IsActive = true,
                            Name = "EcoFarm Pvt Ltd",
                            Password = "client123",
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            ClientId = 8,
                            Address = "56 City Heights",
                            Balance = 0.0,
                            BankId = 8,
                            BankUserId = 8,
                            BusinessType = "Interior Design",
                            Code = "C008",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(4859),
                            Email = "contact@skyline.com",
                            IsActive = true,
                            Name = "Skyline Interiors",
                            Password = "client123",
                            VerificationStatus = "Pending"
                        },
                        new
                        {
                            ClientId = 9,
                            Address = "77 Data Dr",
                            Balance = 0.0,
                            BankId = 9,
                            BankUserId = 9,
                            BusinessType = "Data Analytics",
                            Code = "C009",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(4861),
                            Email = "admin@fincore.com",
                            IsActive = true,
                            Name = "FinCore Analytics",
                            Password = "client123",
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            ClientId = 10,
                            Address = "19 Market Lane",
                            Balance = 0.0,
                            BankId = 10,
                            BankUserId = 10,
                            BusinessType = "Retail Chain",
                            Code = "C010",
                            CreatedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(4863),
                            Email = "info@novaretail.com",
                            IsActive = true,
                            Name = "Nova Retail",
                            Password = "client123",
                            VerificationStatus = "Pending"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("BankUserId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("DocType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.HasIndex("BankUserId");

                    b.HasIndex("ClientId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            DocumentId = 1,
                            BankUserId = 1,
                            ClientId = 1,
                            DocType = "KYC",
                            Name = "PAN Proof",
                            UploadedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(9040),
                            Url = "/docs/pan1.pdf"
                        },
                        new
                        {
                            DocumentId = 2,
                            BankUserId = 2,
                            ClientId = 2,
                            DocType = "Registration",
                            Name = "Registration Cert",
                            UploadedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(9366),
                            Url = "/docs/reg2.pdf"
                        },
                        new
                        {
                            DocumentId = 3,
                            BankUserId = 3,
                            ClientId = 3,
                            DocType = "Address",
                            Name = "Address Proof",
                            UploadedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(9368),
                            Url = "/docs/address3.pdf"
                        },
                        new
                        {
                            DocumentId = 4,
                            BankUserId = 4,
                            ClientId = 4,
                            DocType = "Business License",
                            Name = "License",
                            UploadedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(9374),
                            Url = "/docs/license4.pdf"
                        },
                        new
                        {
                            DocumentId = 5,
                            BankUserId = 5,
                            ClientId = 5,
                            DocType = "Tax",
                            Name = "GST Certificate",
                            UploadedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(9376),
                            Url = "/docs/gst5.pdf"
                        },
                        new
                        {
                            DocumentId = 6,
                            BankUserId = 6,
                            ClientId = 6,
                            DocType = "Insurance",
                            Name = "Insurance Proof",
                            UploadedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(9377),
                            Url = "/docs/ins6.pdf"
                        },
                        new
                        {
                            DocumentId = 7,
                            BankUserId = 7,
                            ClientId = 7,
                            DocType = "Property",
                            Name = "Office Lease",
                            UploadedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(9379),
                            Url = "/docs/lease7.pdf"
                        },
                        new
                        {
                            DocumentId = 8,
                            BankUserId = 8,
                            ClientId = 8,
                            DocType = "KYC",
                            Name = "PAN Proof",
                            UploadedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(9380),
                            Url = "/docs/pan8.pdf"
                        },
                        new
                        {
                            DocumentId = 9,
                            BankUserId = 9,
                            ClientId = 9,
                            DocType = "Financial",
                            Name = "Audit Report",
                            UploadedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(9382),
                            Url = "/docs/audit9.pdf"
                        },
                        new
                        {
                            DocumentId = 10,
                            BankUserId = 10,
                            ClientId = 10,
                            DocType = "Tax",
                            Name = "Tax Return",
                            UploadedAt = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(9383),
                            Url = "/docs/tax10.pdf"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfscCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ClientId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Banking_Payments.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BankUserId")
                        .HasColumnType("int");

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("int");

                    b.Property<int?>("BeneficiaryId1")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("BankUserId");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("BeneficiaryId1");

                    b.HasIndex("ClientId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 10000m,
                            BankUserId = 1,
                            BeneficiaryId = 1,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(7057),
                            Type = 2,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 25000m,
                            BankUserId = 2,
                            BeneficiaryId = 2,
                            ClientId = 2,
                            PaymentDate = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(7859),
                            Type = 0,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 5000m,
                            BankUserId = 3,
                            BeneficiaryId = 3,
                            ClientId = 3,
                            PaymentDate = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(7862),
                            Type = 1,
                            status = 0
                        },
                        new
                        {
                            PaymentId = 4,
                            Amount = 40000m,
                            BankUserId = 4,
                            BeneficiaryId = 4,
                            ClientId = 4,
                            PaymentDate = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(7864),
                            Type = 0,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 5,
                            Amount = 12000m,
                            BankUserId = 5,
                            BeneficiaryId = 5,
                            ClientId = 5,
                            PaymentDate = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(7866),
                            Type = 2,
                            status = -1
                        },
                        new
                        {
                            PaymentId = 6,
                            Amount = 8700m,
                            BankUserId = 6,
                            BeneficiaryId = 6,
                            ClientId = 6,
                            PaymentDate = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(7868),
                            Type = 1,
                            status = 0
                        },
                        new
                        {
                            PaymentId = 7,
                            Amount = 65500m,
                            BankUserId = 7,
                            BeneficiaryId = 7,
                            ClientId = 7,
                            PaymentDate = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(7895),
                            Type = 0,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 8,
                            Amount = 9200m,
                            BankUserId = 8,
                            BeneficiaryId = 8,
                            ClientId = 8,
                            PaymentDate = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(7897),
                            Type = 2,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 9,
                            Amount = 11100m,
                            BankUserId = 9,
                            BeneficiaryId = 9,
                            ClientId = 9,
                            PaymentDate = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(7899),
                            Type = 1,
                            status = 0
                        },
                        new
                        {
                            PaymentId = 10,
                            Amount = 25000m,
                            BankUserId = 10,
                            BeneficiaryId = 10,
                            ClientId = 10,
                            PaymentDate = new DateTime(2025, 11, 4, 13, 49, 28, 260, DateTimeKind.Utc).AddTicks(7900),
                            Type = 0,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 11,
                            Amount = 8500m,
                            BankUserId = 1,
                            BeneficiaryId = 1,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 2, 10, 10, 30, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 12,
                            Amount = 15200m,
                            BankUserId = 11,
                            BeneficiaryId = 1,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 2, 11, 11, 15, 0, 0, DateTimeKind.Utc),
                            Type = 2,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 13,
                            Amount = 23000m,
                            BankUserId = 1,
                            BeneficiaryId = 1,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 2, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0,
                            status = 0
                        },
                        new
                        {
                            PaymentId = 14,
                            Amount = 4200m,
                            BankUserId = 1,
                            BeneficiaryId = 1,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 2, 12, 13, 45, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            status = -1
                        },
                        new
                        {
                            PaymentId = 15,
                            Amount = 12500m,
                            BankUserId = 1,
                            BeneficiaryId = 1,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 2, 13, 8, 20, 0, 0, DateTimeKind.Utc),
                            Type = 2,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 16,
                            Amount = 9900m,
                            BankUserId = 11,
                            BeneficiaryId = 1,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 2, 13, 15, 10, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            status = 0
                        },
                        new
                        {
                            PaymentId = 17,
                            Amount = 30500m,
                            BankUserId = 1,
                            BeneficiaryId = 1,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 2, 14, 10, 5, 0, 0, DateTimeKind.Utc),
                            Type = 0,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 18,
                            Amount = 17800m,
                            BankUserId = 1,
                            BeneficiaryId = 1,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 2, 15, 9, 40, 0, 0, DateTimeKind.Utc),
                            Type = 2,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 19,
                            Amount = 6200m,
                            BankUserId = 1,
                            BeneficiaryId = 1,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 2, 15, 17, 30, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            status = 0
                        },
                        new
                        {
                            PaymentId = 20,
                            Amount = 28500m,
                            BankUserId = 2,
                            BeneficiaryId = 1,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 2, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0,
                            status = 1
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.SalaryDisbursement", b =>
                {
                    b.Property<int>("SalaryDisbursementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryDisbursementId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("SalaryDisbursementId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryDisbursements");
                });

            modelBuilder.Entity("Banking_Payments.Models.Bank", b =>
                {
                    b.HasOne("Banking_Payments.Models.Admin", "Admin")
                        .WithMany("Banks")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Banking_Payments.Models.BankUser", b =>
                {
                    b.HasOne("Banking_Payments.Models.Bank", "Bank")
                        .WithMany("BankUsers")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Banking_Payments.Models.Beneficiary", b =>
                {
                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.Client", null)
                        .WithMany("Beneficiaries")
                        .HasForeignKey("ClientId1");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Banking_Payments.Models.Client", b =>
                {
                    b.HasOne("Banking_Payments.Models.BankUser", "ApprovedByBankUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Banking_Payments.Models.Bank", "Bank")
                        .WithMany("Clients")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.BankUser", "BankUser")
                        .WithMany("Clients")
                        .HasForeignKey("BankUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovedByBankUser");

                    b.Navigation("Bank");

                    b.Navigation("BankUser");
                });

            modelBuilder.Entity("Banking_Payments.Models.Document", b =>
                {
                    b.HasOne("Banking_Payments.Models.BankUser", "UploadedBy")
                        .WithMany("Documents")
                        .HasForeignKey("BankUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany("Documents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Banking_Payments.Models.Employee", b =>
                {
                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany("Employees")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Banking_Payments.Models.Payment", b =>
                {
                    b.HasOne("Banking_Payments.Models.BankUser", "ApprovedBy")
                        .WithMany("Payments")
                        .HasForeignKey("BankUserId");

                    b.HasOne("Banking_Payments.Models.Beneficiary", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.Beneficiary", null)
                        .WithMany("Payments")
                        .HasForeignKey("BeneficiaryId1");

                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Beneficiary");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Banking_Payments.Models.SalaryDisbursement", b =>
                {
                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany("SalaryDisbursement")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.Employee", "Employee")
                        .WithMany("SalaryDisbursements")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Banking_Payments.Models.Admin", b =>
                {
                    b.Navigation("Banks");
                });

            modelBuilder.Entity("Banking_Payments.Models.Bank", b =>
                {
                    b.Navigation("BankUsers");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Banking_Payments.Models.BankUser", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Documents");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Banking_Payments.Models.Beneficiary", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Banking_Payments.Models.Client", b =>
                {
                    b.Navigation("Beneficiaries");

                    b.Navigation("Documents");

                    b.Navigation("Employees");

                    b.Navigation("Payments");

                    b.Navigation("SalaryDisbursement");
                });

            modelBuilder.Entity("Banking_Payments.Models.Employee", b =>
                {
                    b.Navigation("SalaryDisbursements");
                });
#pragma warning restore 612, 618
        }
    }
}
