// <auto-generated />
using System;
using Banking_Payments.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banking_Payments.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Banking_Payments.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Code = "ADM001",
                            Email = "admin@bankingsys.com",
                            Name = "Super Admin",
                            Password = "admin123"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByAdminId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BankId");

                    b.HasIndex("CreatedByAdminId");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            BankId = 1,
                            Address = "Headquarters Tower 1, Connaught Place, New Delhi",
                            Code = "BNK001",
                            ContactEmail = "info1@globalbank.com",
                            ContactPhone = "987650001",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(2386),
                            CreatedByAdminId = 1,
                            IsActive = true,
                            Name = "Global Bank 1",
                            PanNumber = "PANBANK1XYZ",
                            RegistrationNumber = "REG1BANK2025"
                        },
                        new
                        {
                            BankId = 2,
                            Address = "Headquarters Tower 2, Connaught Place, New Delhi",
                            Code = "BNK002",
                            ContactEmail = "info2@globalbank.com",
                            ContactPhone = "987650002",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(2749),
                            CreatedByAdminId = 1,
                            IsActive = true,
                            Name = "Global Bank 2",
                            PanNumber = "PANBANK2XYZ",
                            RegistrationNumber = "REG2BANK2025"
                        },
                        new
                        {
                            BankId = 3,
                            Address = "Headquarters Tower 3, Connaught Place, New Delhi",
                            Code = "BNK003",
                            ContactEmail = "info3@globalbank.com",
                            ContactPhone = "987650003",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(2831),
                            CreatedByAdminId = 1,
                            IsActive = true,
                            Name = "Global Bank 3",
                            PanNumber = "PANBANK3XYZ",
                            RegistrationNumber = "REG3BANK2025"
                        },
                        new
                        {
                            BankId = 4,
                            Address = "Headquarters Tower 4, Connaught Place, New Delhi",
                            Code = "BNK004",
                            ContactEmail = "info4@globalbank.com",
                            ContactPhone = "987650004",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(2838),
                            CreatedByAdminId = 1,
                            IsActive = true,
                            Name = "Global Bank 4",
                            PanNumber = "PANBANK4XYZ",
                            RegistrationNumber = "REG4BANK2025"
                        },
                        new
                        {
                            BankId = 5,
                            Address = "Headquarters Tower 5, Connaught Place, New Delhi",
                            Code = "BNK005",
                            ContactEmail = "info5@globalbank.com",
                            ContactPhone = "987650005",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(2844),
                            CreatedByAdminId = 1,
                            IsActive = true,
                            Name = "Global Bank 5",
                            PanNumber = "PANBANK5XYZ",
                            RegistrationNumber = "REG5BANK2025"
                        },
                        new
                        {
                            BankId = 6,
                            Address = "Headquarters Tower 6, Connaught Place, New Delhi",
                            Code = "BNK006",
                            ContactEmail = "info6@globalbank.com",
                            ContactPhone = "987650006",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(2857),
                            CreatedByAdminId = 1,
                            IsActive = true,
                            Name = "Global Bank 6",
                            PanNumber = "PANBANK6XYZ",
                            RegistrationNumber = "REG6BANK2025"
                        },
                        new
                        {
                            BankId = 7,
                            Address = "Headquarters Tower 7, Connaught Place, New Delhi",
                            Code = "BNK007",
                            ContactEmail = "info7@globalbank.com",
                            ContactPhone = "987650007",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(2940),
                            CreatedByAdminId = 1,
                            IsActive = true,
                            Name = "Global Bank 7",
                            PanNumber = "PANBANK7XYZ",
                            RegistrationNumber = "REG7BANK2025"
                        },
                        new
                        {
                            BankId = 8,
                            Address = "Headquarters Tower 8, Connaught Place, New Delhi",
                            Code = "BNK008",
                            ContactEmail = "info8@globalbank.com",
                            ContactPhone = "987650008",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(2948),
                            CreatedByAdminId = 1,
                            IsActive = true,
                            Name = "Global Bank 8",
                            PanNumber = "PANBANK8XYZ",
                            RegistrationNumber = "REG8BANK2025"
                        },
                        new
                        {
                            BankId = 9,
                            Address = "Headquarters Tower 9, Connaught Place, New Delhi",
                            Code = "BNK009",
                            ContactEmail = "info9@globalbank.com",
                            ContactPhone = "987650009",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(2954),
                            CreatedByAdminId = 1,
                            IsActive = true,
                            Name = "Global Bank 9",
                            PanNumber = "PANBANK9XYZ",
                            RegistrationNumber = "REG9BANK2025"
                        },
                        new
                        {
                            BankId = 10,
                            Address = "Headquarters Tower 10, Connaught Place, New Delhi",
                            Code = "BNK0010",
                            ContactEmail = "info10@globalbank.com",
                            ContactPhone = "9876500010",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(2964),
                            CreatedByAdminId = 1,
                            IsActive = true,
                            Name = "Global Bank 10",
                            PanNumber = "PANBANK10XYZ",
                            RegistrationNumber = "REG10BANK2025"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.BankUser", b =>
                {
                    b.Property<int>("BankUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankUserId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BankUserId");

                    b.HasIndex("BankId");

                    b.ToTable("BankUsers");

                    b.HasData(
                        new
                        {
                            BankUserId = 1,
                            BankId = 1,
                            Code = "BU001",
                            Email = "alice.kumar@globalbank1.com",
                            Name = "Alice Kumar",
                            Password = "alice123",
                            PhoneNumber = "9000010001"
                        },
                        new
                        {
                            BankUserId = 2,
                            BankId = 1,
                            Code = "BU002",
                            Email = "ravi.singh@globalbank1.com",
                            Name = "Ravi Singh",
                            Password = "ravi123",
                            PhoneNumber = "9000010002"
                        },
                        new
                        {
                            BankUserId = 3,
                            BankId = 1,
                            Code = "BU003",
                            Email = "meena.das@globalbank1.com",
                            Name = "Meena Das",
                            Password = "meena123",
                            PhoneNumber = "9000010003"
                        },
                        new
                        {
                            BankUserId = 4,
                            BankId = 1,
                            Code = "BU004",
                            Email = "suresh.nair@globalbank1.com",
                            Name = "Suresh Nair",
                            Password = "suresh123",
                            PhoneNumber = "9000010004"
                        },
                        new
                        {
                            BankUserId = 5,
                            BankId = 1,
                            Code = "BU005",
                            Email = "tanya.joseph@globalbank1.com",
                            Name = "Tanya Joseph",
                            Password = "tanya123",
                            PhoneNumber = "9000010005"
                        },
                        new
                        {
                            BankUserId = 6,
                            BankId = 1,
                            Code = "BU006",
                            Email = "neeraj.chauhan@globalbank1.com",
                            Name = "Neeraj Chauhan",
                            Password = "neeraj123",
                            PhoneNumber = "9000010006"
                        },
                        new
                        {
                            BankUserId = 7,
                            BankId = 1,
                            Code = "BU007",
                            Email = "rohini.sharma@globalbank1.com",
                            Name = "Rohini Sharma",
                            Password = "rohini123",
                            PhoneNumber = "9000010007"
                        },
                        new
                        {
                            BankUserId = 8,
                            BankId = 1,
                            Code = "BU008",
                            Email = "irfan.malik@globalbank1.com",
                            Name = "Irfan Malik",
                            Password = "irfan123",
                            PhoneNumber = "9000010008"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Beneficiary", b =>
                {
                    b.Property<int>("BeneficiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficiaryId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("IfscCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationShip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeneficiaryId");

                    b.HasIndex("ClientId");

                    b.ToTable("Beneficiaries");

                    b.HasData(
                        new
                        {
                            BeneficiaryId = 1,
                            AccountNumber = "1212121212",
                            BankName = "Global Bank 1",
                            ClientId = 1,
                            IfscCode = "GBNK0010001",
                            Name = "Rohit Sharma",
                            RelationShip = "Supplier"
                        },
                        new
                        {
                            BeneficiaryId = 2,
                            AccountNumber = "1313131313",
                            BankName = "Global Bank 1",
                            ClientId = 1,
                            IfscCode = "GBNK0010002",
                            Name = "Sneha Gupta",
                            RelationShip = "Contractor"
                        },
                        new
                        {
                            BeneficiaryId = 3,
                            AccountNumber = "1414141414",
                            BankName = "Global Bank 1",
                            ClientId = 2,
                            IfscCode = "GBNK0010003",
                            Name = "Vikram Iyer",
                            RelationShip = "Farmer"
                        },
                        new
                        {
                            BeneficiaryId = 4,
                            AccountNumber = "1515151515",
                            BankName = "Global Bank 1",
                            ClientId = 2,
                            IfscCode = "GBNK0010004",
                            Name = "Megha Tiwari",
                            RelationShip = "Vendor"
                        },
                        new
                        {
                            BeneficiaryId = 5,
                            AccountNumber = "1616161616",
                            BankName = "Global Bank 1",
                            ClientId = 3,
                            IfscCode = "GBNK0010005",
                            Name = "Aditi Bose",
                            RelationShip = "Teacher"
                        },
                        new
                        {
                            BeneficiaryId = 6,
                            AccountNumber = "1717171717",
                            BankName = "Global Bank 1",
                            ClientId = 4,
                            IfscCode = "GBNK0010006",
                            Name = "Manish Goel",
                            RelationShip = "Supplier"
                        },
                        new
                        {
                            BeneficiaryId = 7,
                            AccountNumber = "1818181818",
                            BankName = "Global Bank 1",
                            ClientId = 4,
                            IfscCode = "GBNK0010007",
                            Name = "Rahul Prasad",
                            RelationShip = "Consultant"
                        },
                        new
                        {
                            BeneficiaryId = 8,
                            AccountNumber = "1919191919",
                            BankName = "Global Bank 1",
                            ClientId = 5,
                            IfscCode = "GBNK0010008",
                            Name = "Priya Nair",
                            RelationShip = "Doctor"
                        },
                        new
                        {
                            BeneficiaryId = 9,
                            AccountNumber = "2020202020",
                            BankName = "Global Bank 1",
                            ClientId = 5,
                            IfscCode = "GBNK0010009",
                            Name = "Dr. Arvind Rao",
                            RelationShip = "Supplier"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("BankUserId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfscCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisterationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("BankId");

                    b.HasIndex("BankUserId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "Gurgaon, Haryana",
                            Balance = 480000.0,
                            BankId = 1,
                            BankUserId = 1,
                            BusinessType = "IT Services",
                            Code = "CL001",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(5409),
                            Email = "info@technova.com",
                            IsActive = true,
                            Name = "TechNova Pvt Ltd",
                            Password = "tech123",
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            ClientId = 2,
                            Address = "Noida Sector 5",
                            Balance = 210000.0,
                            BankId = 1,
                            BankUserId = 2,
                            BusinessType = "Food Supply Chain",
                            Code = "CL002",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(7386),
                            Email = "contact@greenfoods.com",
                            IsActive = true,
                            Name = "GreenFoods Ltd",
                            Password = "green123",
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            ClientId = 3,
                            Address = "Kolkata, West Bengal",
                            Balance = 75000.0,
                            BankId = 1,
                            BankUserId = 3,
                            BusinessType = "Educational NGO",
                            Code = "CL003",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(7392),
                            Email = "hello@edusmart.org",
                            IsActive = true,
                            Name = "EduSmart Foundation",
                            Password = "edu123",
                            VerificationStatus = "Pending"
                        },
                        new
                        {
                            ClientId = 4,
                            Address = "Pune, Maharashtra",
                            Balance = 325000.0,
                            BankId = 1,
                            BankUserId = 4,
                            BusinessType = "Automotive Parts",
                            Code = "CL004",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(7394),
                            Email = "sales@autoworks.com",
                            IsActive = true,
                            Name = "AutoWorks India",
                            Password = "auto123",
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            ClientId = 5,
                            Address = "Hyderabad, Telangana",
                            Balance = 455000.0,
                            BankId = 1,
                            BankUserId = 5,
                            BusinessType = "Healthcare",
                            Code = "CL005",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(7396),
                            Email = "admin@medcare.com",
                            IsActive = true,
                            Name = "MedCare Diagnostics",
                            Password = "med123",
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            ClientId = 6,
                            Address = "Bangalore, Karnataka",
                            Balance = 180000.0,
                            BankId = 1,
                            BankUserId = 6,
                            BusinessType = "Retail Chain",
                            Code = "CL006",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(7398),
                            Email = "support@quickmart.in",
                            IsActive = true,
                            Name = "QuickMart Retail",
                            Password = "mart123",
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            ClientId = 7,
                            Address = "Mumbai, Maharashtra",
                            Balance = 650000.0,
                            BankId = 1,
                            BankUserId = 7,
                            BusinessType = "Real Estate",
                            Code = "CL007",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(7400),
                            Email = "contact@urbanspaces.in",
                            IsActive = true,
                            Name = "UrbanSpaces Realty",
                            Password = "urban123",
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            ClientId = 8,
                            Address = "Chennai, Tamil Nadu",
                            Balance = 275000.0,
                            BankId = 1,
                            BankUserId = 8,
                            BusinessType = "Software Services",
                            Code = "CL008",
                            CreatedAt = new DateTime(2025, 11, 6, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(7402),
                            Email = "hr@brightware.com",
                            IsActive = true,
                            Name = "BrightWare Solutions",
                            Password = "bright123",
                            VerificationStatus = "Pending"
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("BankUserId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("DocType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.HasIndex("BankUserId");

                    b.HasIndex("ClientId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Banking_Payments.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfscCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ClientId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Banking_Payments.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BankUserId")
                        .HasColumnType("int");

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("BankUserId");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("ClientId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 12500m,
                            BankUserId = 1,
                            BeneficiaryId = 1,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 10, 27, 8, 6, 16, 437, DateTimeKind.Local).AddTicks(9664),
                            Remarks = "Monthly IT Contract",
                            Type = 2,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 7500m,
                            BankUserId = 1,
                            BeneficiaryId = 2,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 11, 1, 8, 6, 16, 438, DateTimeKind.Local).AddTicks(776),
                            Remarks = "Hardware Purchase",
                            Type = 1,
                            status = 0
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 34000m,
                            BankUserId = 2,
                            BeneficiaryId = 3,
                            ClientId = 2,
                            PaymentDate = new DateTime(2025, 10, 30, 8, 6, 16, 438, DateTimeKind.Local).AddTicks(784),
                            Remarks = "Raw Material Payment",
                            Type = 0,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 4,
                            Amount = 15000m,
                            BankUserId = 4,
                            BeneficiaryId = 7,
                            ClientId = 4,
                            PaymentDate = new DateTime(2025, 11, 4, 8, 6, 16, 438, DateTimeKind.Local).AddTicks(787),
                            Remarks = "Consultant Fees",
                            Type = 2,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 5,
                            Amount = 9800m,
                            BankUserId = 5,
                            BeneficiaryId = 9,
                            ClientId = 5,
                            PaymentDate = new DateTime(2025, 11, 5, 8, 6, 16, 438, DateTimeKind.Local).AddTicks(790),
                            Remarks = "Doctor Honorarium",
                            Type = 1,
                            status = 0
                        },
                        new
                        {
                            PaymentId = 6,
                            Amount = 18500m,
                            BankUserId = 5,
                            BeneficiaryId = 9,
                            ClientId = 5,
                            PaymentDate = new DateTime(2025, 11, 3, 8, 6, 16, 438, DateTimeKind.Local).AddTicks(792),
                            Remarks = "Supplier Settlement",
                            Type = 0,
                            status = 1
                        },
                        new
                        {
                            PaymentId = 7,
                            Amount = 5600m,
                            BankUserId = 3,
                            BeneficiaryId = 5,
                            ClientId = 3,
                            PaymentDate = new DateTime(2025, 11, 2, 8, 6, 16, 438, DateTimeKind.Local).AddTicks(794),
                            Remarks = "Teacher Stipend",
                            Type = 2,
                            status = 1
                        });
                });

            modelBuilder.Entity("Banking_Payments.Models.SalaryDisbursement", b =>
                {
                    b.Property<int>("SalaryDisbursementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryDisbursementId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("SalaryDisbursementId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryDisbursements");
                });

            modelBuilder.Entity("Banking_Payments.Models.Bank", b =>
                {
                    b.HasOne("Banking_Payments.Models.Admin", "Admin")
                        .WithMany("Banks")
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Banking_Payments.Models.BankUser", b =>
                {
                    b.HasOne("Banking_Payments.Models.Bank", "Bank")
                        .WithMany("BankUsers")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Banking_Payments.Models.Beneficiary", b =>
                {
                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Banking_Payments.Models.Client", b =>
                {
                    b.HasOne("Banking_Payments.Models.BankUser", "ApprovedByBankUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Banking_Payments.Models.Bank", "Bank")
                        .WithMany("Clients")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.BankUser", "BankUser")
                        .WithMany("Clients")
                        .HasForeignKey("BankUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovedByBankUser");

                    b.Navigation("Bank");

                    b.Navigation("BankUser");
                });

            modelBuilder.Entity("Banking_Payments.Models.Document", b =>
                {
                    b.HasOne("Banking_Payments.Models.BankUser", "UploadedBy")
                        .WithMany("Documents")
                        .HasForeignKey("BankUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany("Documents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Banking_Payments.Models.Employee", b =>
                {
                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany("Employees")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Banking_Payments.Models.Payment", b =>
                {
                    b.HasOne("Banking_Payments.Models.BankUser", "ApprovedBy")
                        .WithMany("Payments")
                        .HasForeignKey("BankUserId");

                    b.HasOne("Banking_Payments.Models.Beneficiary", "Beneficiary")
                        .WithMany("Payments")
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Beneficiary");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Banking_Payments.Models.SalaryDisbursement", b =>
                {
                    b.HasOne("Banking_Payments.Models.Client", "Client")
                        .WithMany("SalaryDisbursement")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banking_Payments.Models.Employee", "Employee")
                        .WithMany("SalaryDisbursements")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Banking_Payments.Models.Admin", b =>
                {
                    b.Navigation("Banks");
                });

            modelBuilder.Entity("Banking_Payments.Models.Bank", b =>
                {
                    b.Navigation("BankUsers");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Banking_Payments.Models.BankUser", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Documents");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Banking_Payments.Models.Beneficiary", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Banking_Payments.Models.Client", b =>
                {
                    b.Navigation("Beneficiaries");

                    b.Navigation("Documents");

                    b.Navigation("Employees");

                    b.Navigation("Payments");

                    b.Navigation("SalaryDisbursement");
                });

            modelBuilder.Entity("Banking_Payments.Models.Employee", b =>
                {
                    b.Navigation("SalaryDisbursements");
                });
#pragma warning restore 612, 618
        }
    }
}
